apiVersion: v2
name: rtd-ms-pi-event-processor
description: Microservice designed to handle events from applications and tkm and split it into smaller message for the payment instrument manager.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"