microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  podAnnotations: { }

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /rtdmspieventprocessor/(.*)
    servicePort: 8080

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  envSecret:
    KAFKA_SASL_JAAS_CONFIG_TKM_PIM: evh-tkm-write-update-token-tkm-write-update-token-sub-key
    KAFKA_RTD_PI_FROM_APP_SASL_JAAS_CONFIG: evh-rtd-pi-from-app-rtd-pi-from-app-consumer-policy-rtd
    KAFKA_RTD_SPLIT_SASL_JAAS_CONFIG: evh-rtd-split-by-pi-rtd-split-by-pi-producer-policy-rtd
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  envConfigMapExternals:
    rtd-ms-pi-event-processor:
      JAVA_TOOL_OPTIONS: JAVA_TOOL_OPTIONS
      APPLICATIONINSIGHTS_ROLE_NAME: APPLICATIONINSIGHTS_ROLE_NAME
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED

    rtd-pi-from-app-consumer:
      KAFKA_RTD_PI_FROM_APP: KAFKA_RTD_PI_FROM_APP
      KAFKA_RTD_PI_FROM_APP_CONSUMER_GROUP: KAFKA_RTD_PI_FROM_APP_CONSUMER_GROUP
      KAFKA_RTD_PI_FROM_APP_BROKER: KAFKA_RTD_PI_FROM_APP_BROKER

    rtd-split-by-pi-producer:
      KAFKA_RTD_SPLIT_TOPIC: KAFKA_RTD_SPLIT_TOPIC
      KAFKA_RTD_SPLIT_BROKER: KAFKA_RTD_SPLIT_BROKER
      KAFKA_RTD_SPLIT_PARTITION_COUNT: KAFKA_RTD_SPLIT_PARTITION_COUNT

    rtd-tkm-write-update-consumer:
      KAFKA_TOPIC_TKM: KAFKA_TOPIC_TKM
      KAFKA_TOPIC_TKM_CONSUMER_GROUP: KAFKA_TOPIC_TKM_CONSUMER_GROUP
      KAFKA_TOPIC_TKM_BROKER: KAFKA_TOPIC_TKM_BROKER