apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtd-ms-pieventprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtd-ms-pieventprocessor
  template:
    metadata:
      labels:
        app: rtd-ms-pieventprocessor
    spec:
      containers:
        - name: rtd-ms-pieventprocessor
          image: rtd-ms-pieventprocessor
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi